const fs = require('fs');
const path = require('path');

// --- 1. Fix src/util.ts (realResolve) ---
let util = fs.readFileSync('src/util.ts', 'utf8');

const utilFix = `function realResolve(p: string): string {
  let cur = path.resolve(p);
  const tail: string[] = [];
  for (;;) {
    try { return path.join(fs.realpathSync(cur), ...tail.reverse()); }
    catch {
      const parent = path.dirname(cur);
      if (parent === cur) return path.resolve(p);
      tail.push(path.basename(cur));
      cur = parent;
    }
  }
}

export function isDangerousPath(p: string, home: string = os.homedir()): boolean {
  const cmp = (s: string) => (process.platform === 'win32' ? s.toLowerCase() : s);
  const norm = realResolve(p);
  const h = realResolve(home);
  if (path.parse(norm).root === norm) return true;
  if (cmp(norm) === cmp(h)) return true;
  if (!cmp(norm).startsWith(cmp(h) + path.sep)) return true;
  const parts = path.relative(h, norm).split(path.sep);
  if (SECRET_DIRS.some((d) => cmp(d) === cmp(parts[0]))) return true;
  if (parts.length === 1 && EXACT_ONLY_DIRS.some((d) => cmp(d) === cmp(parts[0]))) return true;
  return false;
}`;

// Replace the whole isDangerousPath block
util = util.replace(/export function isDangerousPath[\s\S]*?return false;\s*}/, utilFix);
fs.writeFileSync('src/util.ts', util);


// --- 2. Fix main.ts (.gitignore managed block) ---
let main = fs.readFileSync('main.ts', 'utf8');

const gitignoreLogic = `
		const gitignorePath = path.join(vaultPath, '.gitignore');
		const brain = this.settings.vaultBrainFolder || 'AI-Brain';
		
		const blockStart = '### >>> agentic-vault >>>';
		const blockEnd = '### <<< agentic-vault <<<';
		const rules = [
			blockStart,
			'# DO NOT EDIT THIS BLOCK. Auto-generated by Agentic Vault.',
			'# ZERO-TRUST ARCHITECTURE',
			'.obsidian/',
			'/workspace.json',
			'/workspace-mobile.json',
			'node_modules/',
			'.DS_Store',
			\`\${this.app.vault.configDir}/plugins/agentic-vault/secrets.json\`,
			\`\${brain}/**/*\`,
			\`!\${brain}/**/\`,
			'# WHITELIST',
			\`!/\${this.settings.ruleFilePath}\`,
			\`!\${brain}/**/skills/**\`,
			\`!\${brain}/**/.agents/skills/**\`,
			\`!\${brain}/**/CLAUDE.md\`,
			\`!\${brain}/**/GEMINI.md\`,
			\`!\${brain}/**/.cursorrules\`,
			\`!\${brain}/**/.cursor/rules/**\`,
			\`!\${brain}/**/copilot-instructions.md\`,
			\`!\${brain}/**/CONVENTIONS.md\`,
			\`!\${brain}/**/.windsurfrules\`,
			'# BLACKLIST',
			\`\${brain}/**/*[oO][aA][uU][tT][hH]*\`,
			\`\${brain}/**/*[tT][oO][kK][eE][nN]*\`,
			\`\${brain}/**/*[sS][eE][cC][rR][eE][tT]*\`,
			\`\${brain}/**/credentials\`,
			\`\${brain}/**/.env*\`,
			\`\${brain}/**/*.key\`,
			\`\${brain}/**/*.pem\`,
			\`\${brain}/**/*.p12\`,
			\`\${brain}/**/*.pfx\`,
			\`\${brain}/**/id_rsa*\`,
			blockEnd
		].join('\\n');

		try {
			let content = '';
			if (fs.existsSync(gitignorePath)) {
				content = fs.readFileSync(gitignorePath, 'utf8');
			}
			
			const blockRe = new RegExp(\`\\\\n?\\\${blockStart}[\\\\s\\\\S]*?\\\${blockEnd}\\\\n?\`, 'g');
			content = content.replace(blockRe, ''); // remove existing blocks
			content = content.trim();
			content = content ? content + '\\n\\n' + rules + '\\n' : rules + '\\n';
			
			fs.writeFileSync(gitignorePath, content);
		} catch (e) {
			console.error("Failed to update .gitignore", e);
		}
`;

main = main.replace(/const gitignorePath = path\.join\(vaultPath, '\.gitignore'\);[\s\S]*?console\.error\("Failed to update \.gitignore", e\);\n\t\t}/, gitignoreLogic.trim());
fs.writeFileSync('main.ts', main);


// --- 3. Fix src/sync.ts (fail-close, unpushed commits, public check) ---
let sync = fs.readFileSync('src/sync.ts', 'utf8');

// Fix ls-files fail-close
sync = sync.replace(
    /const trackedStr = await git\.raw\(\['ls-files', '-ci', '--exclude-standard', '-z'\]\)\.catch\(\(\) => ''\);/,
    `const trackedStr = await git.raw(['ls-files', '-ci', '--exclude-standard', '-z']); // removed .catch() so it fails closed`
);

// Fix unpushed commits scanning
const scanBlockRe = /\/\/ Scan unpushed commits[\s\S]*?if \(findings\.length > 0\)/;
const newScanBlock = `// Scan unpushed commits using git log -p
      try {
        const unpushedDiff = await git.raw(['log', '-p', '--not', '--remotes=' + remote, 'HEAD']);
        findings = [...findings, ...scanDiff(unpushedDiff)];
      } catch (e) {}

      if (findings.length > 0)`;
sync = sync.replace(scanBlockRe, newScanBlock);

// Fix public check
sync = sync.replace(
    /if \(opts\.allowPublicRemote === false\) \{/,
    `if (!opts.allowPublicRemote) {`
);

fs.writeFileSync('src/sync.ts', sync);
console.log("PATCH2 COMPLETE");
